package hu.bme.aut.android.towerdefenseapp.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFA5C8FF)
val md_theme_dark_onPrimary = Color(0xFF00315E)
val md_theme_dark_primaryContainer = Color(0xFF004785)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_secondary = Color(0xFFBDC7DC)
val md_theme_dark_onSecondary = Color(0xFF273141)
val md_theme_dark_secondaryContainer = Color(0xFF3D4758)
val md_theme_dark_onSecondaryContainer = Color(0xFFD9E3F8)
val md_theme_dark_tertiary = Color(0xFFDEBCDD)
val md_theme_dark_onTertiary = Color(0xFF3F2840)
val md_theme_dark_tertiaryContainer = Color(0xFF573E57)
val md_theme_dark_onTertiaryContainer = Color(0xFFFCD8FB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF0F1218)
val md_theme_dark_onBackground = Color(0xFFE2E2E6)
val md_theme_dark_surface = Color(0xFF1A1D24)
val md_theme_dark_onSurface = Color(0xFFE2E2E6)
val md_theme_dark_surfaceVariant = Color(0xFF2D323C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C7D0)
val md_theme_dark_outline = Color(0xFF8F919A)
val md_theme_dark_inverseOnSurface = Color(0xFF0F1218)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E6)
val md_theme_dark_inversePrimary = Color(0xFF2A5EA7)
val md_theme_dark_surfaceTint = Color(0xFFA5C8FF)
val md_theme_dark_outlineVariant = Color(0xFF44474F)
val md_theme_dark_scrim = Color(0xFF000000)

val easyColor = Color(0xFF4CAF50)
val mediumColor = Color(0xFFFFC107)
val hardColor = Color(0xFFF44336)